---
- name: Configure newly created EC2 instance
  hosts: new_ec2_instances
  become: yes
  gather_facts: yes
  tasks:
    - name: Install Podman
      yum:
        name: podman
        state: present

    - name: Pull HammerDB PostgreSQL container image
      command: podman pull docker.io/tpcorg/hammerdb:postgres

    - name: Deploy HammerDB test scripts
      template:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
      loop:
        - src: "templates/hammerdb-tpcc-setup.tcl.j2"
          dest: "setup.tcl"
        - src: "templates/hammerdb-tpcc-run.tcl.j2"
          dest: "run.tcl"
        - src: "templates/hammerdb-tpcc-cleanup.tcl.j2"   # Not used in the playbook, mean for manual cleanup when rerunning the test manually
          dest: "cleanup.tcl"

    - name: Setup HammerDB test
      shell: |
        cat setup.tcl | podman run --network=host --rm -it --name hammerdb docker.io/tpcorg/hammerdb:postgres ./hammerdbcli
      register: hammerdb_setup_out

    - name: Show test setup output
      debug:
        var: hammerdb_setup_out

    - name: Check test setup was OK
      vars:
        lines_all: "{{ hammerdb_setup_out.stdout_lines | select('match', '.*:FINISHED .*') }}"
        lines_succeeded: "{{ lines_all | select('match', '.*:FINISHED SUCCESS') }}"
      assert:
        that:
          - lines_all|length > 0
          - lines_all|length == lines_succeeded|length

    - name: Run HammerDB test
      shell: |
        cat run.tcl | podman run --network=host --rm -it --name hammerdb docker.io/tpcorg/hammerdb:postgres ./hammerdbcli
      register: hammerdb_run_out

    - name: Show test run output
      debug:
        var: hammerdb_run_out

    - name: Check test run was OK
      vars:
        lines_all: "{{ hammerdb_run_out.stdout_lines | select('match', '.*:FINISHED .*') }}"
        lines_succeeded: "{{ lines_all | select('match', '.*:FINISHED SUCCESS') }}"
      assert:
        that:
          - lines_all|length > 0
          - lines_all|length == lines_succeeded|length

    - name: Parse new orders per minute value out of output
      set_fact:
        result_nopm: "{{ hammerdb_run_out.stdout | regex_search('TEST RESULT : System achieved ([0-9]+) NOPM from [0-9]+ PostgreSQL TPM','\\1') | first }}"

    - name: Parse transactions per minute value out of output
      set_fact:
        result_tpm: "{{ hammerdb_run_out.stdout | regex_search('TEST RESULT : System achieved [0-9]+ NOPM from ([0-9]+) PostgreSQL TPM','\\1') | first }}"

    - name: Show results
      debug:
        msg: "RESULTS: NOPM = {{ result_nopm }}, TPM = {{ result_tpm }}"
